# Generated by Django 5.1.7 on 2025-03-13 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_rename_name_brand_brand_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='client_images')),
                ('role_type', models.CharField(choices=[('client', 'client'), ('owner', 'owner')], default='client', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('client', 'client'), ('owner', 'owner')], max_length=32)),
                ('company_name', models.CharField(max_length=32)),
                ('company_image', models.ImageField(unique='company_images/', upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_brand', to='car_app.brand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_car', to='car_app.category'),
        ),
    ]
